import pluginVue from 'eslint-plugin-vue'
import { defineConfigWithVueTs, vueTsConfigs } from '@vue/eslint-config-typescript'
import skipFormatting from '@vue/eslint-config-prettier/skip-formatting'

// Flat config for the Vue 3 + Vite front-end. Prettier owns formatting, so
// skipFormatting disables ESLint rules that would conflict with it.
export default defineConfigWithVueTs(
  {
    name: 'app/files-to-lint',
    files: ['**/*.{ts,mts,tsx,vue}'],
  },
  {
    name: 'app/files-to-ignore',
    // Generated swagger client (@ts-nocheck, regenerated by `npm run swagger-gen`),
    // build output, and the .NET WASM bundle.
    ignores: ['**/dist/**', '**/public/_framework/**', 'src/lib/FactorioToolsApi.ts'],
  },
  pluginVue.configs['flat/essential'],
  vueTsConfigs.recommended,
  skipFormatting,
  {
    name: 'app/rules',
    rules: {
      // Allow intentionally-unused identifiers prefixed with `_` (e.g. `(_) => ...`).
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
        },
      ],
    },
  },
)
