-- Generated by CSharp.lua Compiler
local System = System
local KnapcodeOilField
local ListLocation
local SpanLocation
local ArrayLocation
local QueueLocation
System.import(function (out)
  KnapcodeOilField = Knapcode.FactorioTools.OilField
  ListLocation = System.List(KnapcodeOilField.Location)
  SpanLocation = System.Span(KnapcodeOilField.Location)
  ArrayLocation = System.Array(KnapcodeOilField.Location)
  QueueLocation = System.Queue(KnapcodeOilField.Location)
end)
System.namespace("Knapcode.FactorioTools.OilField", function (namespace)
  -- <summary>
  -- Routes a single connected heat pipe network adjacent to every pumpjack and every pipe so the oil field can survive
  -- on Aquilo (Factorio 2.0 / Space Age), where unheated entities freeze. Heat conducts through the heat pipe network, so
  -- every pumpjack and pipe only needs one adjacent heat pipe; the network is grown as one connected component so heat
  -- from a single (user-placed) heat source reaches all of it.
  -- This runs after the pumpjacks, pipes, underground pipes, and electric poles are on the grid and fills remaining empty
  -- tiles. The covering + connectivity problem is NP-hard, so this is a greedy heuristic that grows one connected network:
  -- it seeds with the highest-coverage tile, then repeatedly adds the network-adjacent tile that covers the most still
  -- uncovered targets, bridging across gaps with a breadth-first search when no adjacent tile makes progress. Growing a
  -- single connected component guarantees both coverage and connectivity without dropping any covering tiles.
  -- </summary>
  namespace.class("AddHeatPipes", function (namespace)
    local PumpjackRingOffsets, Execute, Route, RouteCore, Grow, GrowFrom, ExtendToBeacons, Gain, 
    HasEmptyNeighbor, IsAdjacentToNetwork, AddTile, AddCoverage, CountCovered, RemoveCovered, BridgeToTile, static
    static = function (this)
      PumpjackRingOffsets = ArrayLocation(12, {
        KnapcodeOilField.Location(- 1, - 2),
        KnapcodeOilField.Location(0, - 2),
        KnapcodeOilField.Location(1, - 2),
        KnapcodeOilField.Location(- 1, 2),
        KnapcodeOilField.Location(0, 2),
        KnapcodeOilField.Location(1, 2),
        KnapcodeOilField.Location(- 2, - 1),
        KnapcodeOilField.Location(- 2, 0),
        KnapcodeOilField.Location(- 2, 1),
        KnapcodeOilField.Location(2, - 1),
        KnapcodeOilField.Location(2, 0),
        KnapcodeOilField.Location(2, 1)
      })
      this.PumpjackRingOffsets = PumpjackRingOffsets
    end
    Execute = function (context)
      -- When beacons are also enabled, the heat network was already routed (before beacon planning) and
      -- placed during AddPipes so beacons could route around it. Don't re-route over the placed entities.
      if not context.Options.AddHeatPipes or context.HeatPipes ~= nil then
        return
      end

      local grid = context.Grid

      -- Collect the targets that must be heated: every pipe tile, and every pumpjack center.
      local pipeTiles = context:GetLocationSet2(true)
      for _, location in System.each(grid:getEntityLocations():EnumerateItems()) do
        if System.is(grid:get(location), KnapcodeOilField.Pipe) then
          pipeTiles:Add(location)
        end
      end

      local default, _, _ = RouteCore(context, pipeTiles)
      local chosen = default

      -- Place the heat pipe entities.
      for _, location in System.each(chosen:EnumerateItems()) do
        grid:AddEntity(location, KnapcodeOilField.HeatPipe(grid:GetId()))
      end

      context.HeatPipes = chosen
    end
    -- <summary>
    -- Routes the heat pipe network for a given set of pipe tiles and returns the chosen heat tiles without placing any
    -- entities. The caller must have the pipe tiles occupying the grid (so they are not considered empty) - this lets
    -- beacon planning route heat first and place beacons around it. The grid is left unchanged.
    -- <paramref name="uncoveredPipes"/> and <paramref name="uncoveredCenters"/> are non-empty when this pipe layout
    -- cannot be fully heated (some pipe or pumpjack has no reachable empty tile); the caller ranks by these counts.
    -- </summary>
    Route = function (context, pipeTiles, uncoveredPipes, uncoveredCenters)
      local grid = context.Grid

      for _, pipe in System.each(pipeTiles:EnumerateItems()) do
        grid:AddEntity(pipe, KnapcodeOilField.TemporaryEntity(grid:GetId()))
      end

      local default
      default, uncoveredPipes, uncoveredCenters = RouteCore(context, pipeTiles)
      local chosen = default

      for _, pipe in System.each(pipeTiles:EnumerateItems()) do
        grid:RemoveEntity(pipe)
      end

      return chosen, uncoveredPipes, uncoveredCenters
    end
    -- <summary>
    -- The core greedy routing: builds candidate heat tiles from the targets and grows one connected network covering
    -- them. Assumes the pipe tiles (and pumpjacks) already occupy the grid so candidate tiles are genuinely empty.
    -- </summary>
    RouteCore = function (context, pipeTiles, uncoveredPipesOut, uncoveredCentersOut)
      local grid = context.Grid

      -- Build candidate heat pipe tiles (empty tiles that cover at least one target) and what each one covers.
      local candidates = ListLocation()
      local coveredPipes = context:GetLocationDictionary(ListLocation)
      local coveredCenters = context:GetLocationDictionary(ListLocation)

      local adjacent = SpanLocation.ctorArray(ArrayLocation(4))


      for _, pipe in System.each(pipeTiles:EnumerateItems()) do
        local continue
        repeat
          grid:GetAdjacent(adjacent, pipe)
          for i = 0, adjacent:getLength() - 1 do
            local continue
            repeat
              local candidate = adjacent:get(i)
              if not candidate.IsValid or not grid:IsEmpty(candidate) then
                continue = true
                break
              end

              AddCoverage(coveredPipes, candidates, candidate, pipe)
              continue = true
            until 1
            if not continue then
              break
            end
          end
          continue = true
        until 1
        if not continue then
          break
        end
      end

      for c = 0, #context.Centers - 1 do
        local continue
        repeat
          local center = context.Centers:get(c)
          for i = 0, #PumpjackRingOffsets - 1 do
            local continue
            repeat
              local candidate = center:Translate1(PumpjackRingOffsets:get(i))
              if not grid:IsInBounds(candidate) or not grid:IsEmpty(candidate) then
                continue = true
                break
              end

              AddCoverage(coveredCenters, candidates, candidate, center)
              continue = true
            until 1
            if not continue then
              break
            end
          end
          continue = true
        until 1
        if not continue then
          break
        end
      end

      local chosen = context:GetLocationSet2(true)

      local uncoveredPipes = context:GetLocationSet2(true)
      uncoveredPipes:UnionWith1(pipeTiles)
      local uncoveredCenters = context:GetLocationSet2(true)
      for c = 0, #context.Centers - 1 do
        uncoveredCenters:Add(context.Centers:get(c))
      end

      if #candidates > 0 then
        Grow(context, chosen, candidates, coveredPipes, coveredCenters, uncoveredPipes, uncoveredCenters)
      end

      uncoveredPipesOut = uncoveredPipes
      uncoveredCentersOut = uncoveredCenters

      return chosen, uncoveredPipesOut, uncoveredCentersOut
    end
    -- <summary>
    -- Grows a single connected heat pipe network. Seeds with the highest-coverage candidate, then repeatedly adds the
    -- network-adjacent candidate with the most uncovered coverage; when no adjacent candidate makes progress it bridges
    -- to the best remaining candidate via a shortest empty-tile path. Stops when everything reachable is covered.
    -- </summary>
    Grow = function (context, chosen, candidates, coveredPipes, coveredCenters, uncoveredPipes, uncoveredCenters)
      local grid = context.Grid

      local adjacent = SpanLocation.ctorArray(ArrayLocation(4))


      -- Seed with the candidate that covers the most targets, but prefer one the network can actually grow from: a
      -- candidate with at least one empty orthogonal neighbor ("expandable"). The highest-coverage tile can be fully
      -- enclosed by pumpjacks and pipes (e.g. a tile wedged between two pumpjacks and two pipe runs). Bridging always
      -- walks outward from the chosen network through empty tiles, so an enclosed seed can never expand and the rest
      -- of the field is abandoned. Falling back to the plain best only when nothing is expandable.
      local seed = KnapcodeOilField.Location.getInvalid()
      local seedGain = - 1
      local expandableSeed = KnapcodeOilField.Location.getInvalid()
      local expandableSeedGain = - 1
      for i = 0, #candidates - 1 do
        local candidate = candidates:get(i)
        local gain = Gain(coveredPipes, coveredCenters, candidate, uncoveredPipes, uncoveredCenters)
        if gain > seedGain then
          seedGain = gain
          seed = candidate
        end

        if gain > expandableSeedGain and HasEmptyNeighbor(grid, candidate, adjacent) then
          expandableSeedGain = gain
          expandableSeed = candidate
        end
      end

      if expandableSeed.IsValid then
        seed = expandableSeed
      end

      AddTile(coveredPipes, coveredCenters, chosen, seed, uncoveredPipes, uncoveredCenters)

      GrowFrom(context, chosen, candidates, coveredPipes, coveredCenters, uncoveredPipes, uncoveredCenters)
    end
    -- <summary>
    -- Grows an already-seeded connected network (<paramref name="chosen"/> must be non-empty) until every reachable
    -- uncovered target is covered, bridging through empty tiles when no adjacent candidate makes progress.
    -- </summary>
    GrowFrom = function (context, chosen, candidates, coveredPipes, coveredCenters, uncoveredPipes, uncoveredCenters)
      local adjacent = SpanLocation.ctorArray(ArrayLocation(4))


      -- Candidates we could not reach by bridging; skip them on later passes to avoid looping.
      local unreachable = context:GetLocationSet1()

      while uncoveredPipes:getCount() > 0 or uncoveredCenters:getCount() > 0 do
        local continue
        repeat
          -- Fast path: the best candidate orthogonally adjacent to the current network (keeps it connected for free).
          local bestAdjacent = KnapcodeOilField.Location.getInvalid()
          local bestAdjacentGain = 0

          -- Bridge fallback: the best candidate anywhere that still covers something and we have not failed to reach.
          local bestAny = KnapcodeOilField.Location.getInvalid()
          local bestAnyGain = 0

          for i = 0, #candidates - 1 do
            local continue
            repeat
              local candidate = candidates:get(i)
              if chosen:Contains(candidate) then
                continue = true
                break
              end

              local gain = Gain(coveredPipes, coveredCenters, candidate, uncoveredPipes, uncoveredCenters)
              if gain == 0 then
                continue = true
                break
              end

              if not unreachable:Contains(candidate) and gain > bestAnyGain then
                bestAnyGain = gain
                bestAny = candidate
              end

              if gain > bestAdjacentGain and IsAdjacentToNetwork(context.Grid, chosen, candidate, adjacent) then
                bestAdjacentGain = gain
                bestAdjacent = candidate
              end
              continue = true
            until 1
            if not continue then
              break
            end
          end

          if bestAdjacentGain > 0 then
            AddTile(coveredPipes, coveredCenters, chosen, bestAdjacent, uncoveredPipes, uncoveredCenters)
            continue = true
            break
          end

          if bestAnyGain == 0 then
            -- Remaining targets have no empty candidate tile at all - they are boxed in and cannot be heated.
            break
          end

          -- Bridge the network out to the best remaining candidate.
          local path = BridgeToTile(context, chosen, bestAny)
          if path == nil then
            unreachable:Add(bestAny)
            continue = true
            break
          end

          for i = 0, #path - 1 do
            AddTile(coveredPipes, coveredCenters, chosen, path:get(i), uncoveredPipes, uncoveredCenters)
          end
          continue = true
        until 1
        if not continue then
          break
        end
      end
    end
    -- <summary>
    -- Extends the already-placed heat network (<see cref="Context.HeatPipes"/>) to reach the placed beacons. A beacon
    -- is heated when a heat pipe is orthogonally adjacent to its footprint. The footprint is derived from
    -- <see cref="OilFieldOptions.BeaconWidth"/> / <see cref="OilFieldOptions.BeaconHeight"/> so custom beacon sizes
    -- work. New heat tiles are placed on the grid and added to <see cref="Context.HeatPipes"/>. Returns the set of
    -- beacon center locations that ended up heated; beacons not in the set are boxed in and cannot be heated.
    -- </summary>
    ExtendToBeacons = function (context, beaconCenters)
      local grid = context.Grid
      local heatedBeacons = context:GetLocationSet2(true)

      if context.HeatPipes == nil or beaconCenters:getCount() == 0 then
        return heatedBeacons
      end

      local width = context.Options.BeaconWidth
      local height = context.Options.BeaconHeight

      local uncoveredBeacons = context:GetLocationSet2(true)
      for i = 0, beaconCenters:getCount() - 1 do
        uncoveredBeacons:Add(beaconCenters:get(i))
      end

      local candidates = ListLocation()
      local coveredBeacons = context:GetLocationDictionary(ListLocation)

      -- Empty placeholders for the pipe coverage channel that GrowFrom shares with the pumpjack/pipe router.
      local noPipeCoverage = context:GetLocationDictionary(ListLocation)
      local noPipes = context:GetLocationSet2(true)

      local adjacent = SpanLocation.ctorArray(ArrayLocation(4))


      for b = 0, beaconCenters:getCount() - 1 do
        local continue
        repeat
          local center = beaconCenters:get(b)
          local minX = center.X - (System.div((width - 1), 2))
          local maxX = center.X + (System.div(width, 2))
          local minY = center.Y - (System.div((height - 1), 2))
          local maxY = center.Y + (System.div(height, 2))

          -- First pass: is this beacon already adjacent to the existing network?
          local alreadyHeated = false
          do
            local x = minX
            while x <= maxX and not alreadyHeated do
              do
                local y = minY
                while y <= maxY and not alreadyHeated do
                  grid:GetAdjacent(adjacent, KnapcodeOilField.Location(x, y))
                  for i = 0, adjacent:getLength() - 1 do
                    local n = adjacent:get(i)
                    if n.IsValid and System.is(grid:get(n), KnapcodeOilField.HeatPipe) then
                      alreadyHeated = true
                      break
                    end
                  end
                  y = y + 1
                end
              end
              x = x + 1
            end
          end

          if alreadyHeated then
            uncoveredBeacons:Remove(center)
            continue = true
            break
          end

          -- Second pass: register empty footprint-adjacent tiles as candidates that would heat this beacon.
          for x = minX, maxX do
            local continue
            repeat
              for y = minY, maxY do
                local continue
                repeat
                  grid:GetAdjacent(adjacent, KnapcodeOilField.Location(x, y))
                  for i = 0, adjacent:getLength() - 1 do
                    local continue
                    repeat
                      local n = adjacent:get(i)
                      if not n.IsValid then
                        continue = true
                        break
                      end

                      local insideFootprint = n.X >= minX and n.X <= maxX and n.Y >= minY and n.Y <= maxY
                      if not insideFootprint and grid:IsEmpty(n) then
                        AddCoverage(coveredBeacons, candidates, n, center)
                      end
                      continue = true
                    until 1
                    if not continue then
                      break
                    end
                  end
                  continue = true
                until 1
                if not continue then
                  break
                end
              end
              continue = true
            until 1
            if not continue then
              break
            end
          end
          continue = true
        until 1
        if not continue then
          break
        end
      end

      -- Seed the grow with the entire existing network so the extension stays one connected component.
      local chosen = context:GetLocationSet2(true)
      chosen:UnionWith1(context.HeatPipes)

      if #candidates > 0 and uncoveredBeacons:getCount() > 0 then
        GrowFrom(context, chosen, candidates, noPipeCoverage, coveredBeacons, noPipes, uncoveredBeacons)
      end

      -- Place the newly chosen tiles (chosen minus the pre-existing network) and grow the network set.
      for _, location in System.each(chosen:EnumerateItems()) do
        local continue
        repeat
          if context.HeatPipes:Contains(location) then
            continue = true
            break
          end

          grid:AddEntity(location, KnapcodeOilField.HeatPipe(grid:GetId()))
          context.HeatPipes:Add(location)
          continue = true
        until 1
        if not continue then
          break
        end
      end

      for i = 0, beaconCenters:getCount() - 1 do
        if not uncoveredBeacons:Contains(beaconCenters:get(i)) then
          heatedBeacons:Add(beaconCenters:get(i))
        end
      end

      return heatedBeacons
    end
    Gain = function (coveredPipes, coveredCenters, candidate, uncoveredPipes, uncoveredCenters)
      return CountCovered(coveredPipes, candidate, uncoveredPipes) + CountCovered(coveredCenters, candidate, uncoveredCenters)
    end
    HasEmptyNeighbor = function (grid, location, adjacent)
      grid:GetAdjacent(adjacent, location)
      for i = 0, adjacent:getLength() - 1 do
        if adjacent:get(i).IsValid and grid:IsEmpty(adjacent:get(i)) then
          return true
        end
      end

      return false
    end
    IsAdjacentToNetwork = function (grid, chosen, candidate, adjacent)
      grid:GetAdjacent(adjacent, candidate)
      for i = 0, adjacent:getLength() - 1 do
        if adjacent:get(i).IsValid and chosen:Contains(adjacent:get(i)) then
          return true
        end
      end

      return false
    end
    AddTile = function (coveredPipes, coveredCenters, chosen, location, uncoveredPipes, uncoveredCenters)
      if not chosen:Add(location) then
        return
      end

      RemoveCovered(coveredPipes, location, uncoveredPipes)
      RemoveCovered(coveredCenters, location, uncoveredCenters)
    end
    AddCoverage = function (covered, candidates, candidate, target)
      local default, targets = covered:TryGetValue(candidate)
      if not default then
        targets = ListLocation()
        covered:Add(candidate, targets)
        candidates:Add(candidate)
      end

      targets:Add(target)
    end
    CountCovered = function (covered, candidate, uncovered)
      local default, targets = covered:TryGetValue(candidate)
      if not default then
        return 0
      end

      local count = 0
      for i = 0, #targets - 1 do
        if uncovered:Contains(targets:get(i)) then
          count = count + 1
        end
      end

      return count
    end
    RemoveCovered = function (covered, candidate, uncovered)
      local default, targets = covered:TryGetValue(candidate)
      if not default then
        return
      end

      for i = 0, #targets - 1 do
        uncovered:Remove(targets:get(i))
      end
    end
    -- <summary>
    -- Finds the shortest path of empty tiles from the current network (any chosen tile) to <paramref name="goal"/>,
    -- inclusive of both ends. Returns null if the goal cannot be reached through empty tiles. Chosen tiles are still
    -- empty at this stage (placement is deferred), so the search can travel along the existing network.
    -- </summary>
    BridgeToTile = function (context, chosen, goal)
      local grid = context.Grid
      local queue = QueueLocation()
      local visited = context:GetLocationSet1()
      local parents = context:GetLocationDictionary(KnapcodeOilField.Location)

      for _, location in System.each(chosen:EnumerateItems()) do
        queue:Enqueue(location)
      end

      local neighbors = SpanLocation.ctorArray(ArrayLocation(4))


      while #queue > 0 do
        local continue
        repeat
          local current = queue:Dequeue()
          if not visited:Add(current) then
            continue = true
            break
          end

          if KnapcodeOilField.Location.op_Equality(current, goal) then
            local default = ListLocation()
            default:Add(current)
            local path = default
            while true do
              local default, parent = parents:TryGetValue(current)
              if not default then
                break
              end
              path:Add(parent)
              current = parent
            end

            return path
          end

          grid:GetNeighbors(neighbors, current)
          for i = 0, neighbors:getLength() - 1 do
            local continue
            repeat
              local next = neighbors:get(i)
              if not next.IsValid or visited:Contains(next) or not parents:TryAdd(next, current) then
                continue = true
                break
              end

              queue:Enqueue(next)
              continue = true
            until 1
            if not continue then
              break
            end
          end
          continue = true
        until 1
        if not continue then
          break
        end
      end

      return nil
    end
    return {
      Execute = Execute,
      Route = Route,
      ExtendToBeacons = ExtendToBeacons,
      static = static
    }
  end)
end)
