-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Knapcode.FactorioTools.OilField", function (namespace)
  -- <summary>
  -- A summary of the various oil field plans attempted.
  -- </summary>
  -- <param name="MissingPumpjacks">The number of pumpjacks removed to allow for electric poles. This must be zero.</param>
  -- <param name="RotatedPumpjacks">The number of pumpjacks that were rotated from their original position.</param>
  -- <param name="HeatDroppedPumpjacks">Pumpjacks dropped so the rest of the field could be fully heated on Aquilo. Zero unless heat pipes are enabled.</param>
  -- <param name="UnheatedPumpjacks">Pumpjacks still left without an adjacent heat pipe in the final output (normally zero).</param>
  -- <param name="UnheatedPipes">Pipe tiles still left without an adjacent heat pipe in the final output (normally zero).</param>
  -- <param name="SelectedPlans">The set of plans which exactly the same and determined to be the best.</param>
  -- <param name="AlternatePlans">The set of plans which are equivalent to the selected plans by ranking but not exactly the same.</param>
  -- <param name="UnusedPlans">The set of plans that were not the best and were discarded.</param>
  namespace.class("OilFieldPlanSummary", function (namespace)
    local __members__, __ctor__
    __ctor__ = function (this, MissingPumpjacks, RotatedPumpjacks, HeatDroppedPumpjacks, UnheatedPumpjacks, UnheatedPipes, SelectedPlans, AlternatePlans, UnusedPlans)
      this.MissingPumpjacks = MissingPumpjacks
      this.RotatedPumpjacks = RotatedPumpjacks
      this.HeatDroppedPumpjacks = HeatDroppedPumpjacks
      this.UnheatedPumpjacks = UnheatedPumpjacks
      this.UnheatedPipes = UnheatedPipes
      this.SelectedPlans = SelectedPlans
      this.AlternatePlans = AlternatePlans
      this.UnusedPlans = UnusedPlans
    end
    __members__ = function ()
      return "OilFieldPlanSummary", "MissingPumpjacks", "RotatedPumpjacks", "HeatDroppedPumpjacks", "UnheatedPumpjacks", "UnheatedPipes", "SelectedPlans", "AlternatePlans", "UnusedPlans"
    end
    return {
      MissingPumpjacks = 0,
      RotatedPumpjacks = 0,
      HeatDroppedPumpjacks = 0,
      UnheatedPumpjacks = 0,
      UnheatedPipes = 0,
      base = function (out)
        return {
          System.RecordType,
          System.IEquatable_1(out.Knapcode.FactorioTools.OilField.OilFieldPlanSummary)
        }
      end,
      __members__ = __members__,
      __ctor__ = __ctor__
    }
  end)
end)
