-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Knapcode.FactorioTools.OilField", function (namespace)

  namespace.class("Qualities", function (namespace)
    local ToBlueprintString
    -- <summary>
    -- The lowercase quality name used in blueprint JSON (e.g. "legendary"). "normal" is the default
    -- and is omitted from output by callers.
    -- </summary>
    ToBlueprintString = function (quality)
      repeat
        if quality == 1 --[[Quality.Uncommon]] then
          return "uncommon"
        elseif quality == 2 --[[Quality.Rare]] then
          return "rare"
        elseif quality == 3 --[[Quality.Epic]] then
          return "epic"
        elseif quality == 5 --[[Quality.Legendary]] then
          return "legendary"
        else
          return "normal"
        end
      until 1
    end
    return {
      ToBlueprintString = ToBlueprintString
    }
  end)
end)
