-- Generated by CSharp.lua Compiler
local System = System
local KnapcodeFactorioTools
local KnapcodeOilField
local ListLocation
local SpanLocation
local ArrayLocation
local QueueLocation
System.import(function (out)
  KnapcodeFactorioTools = Knapcode.FactorioTools
  KnapcodeOilField = Knapcode.FactorioTools.OilField
  ListLocation = System.List(KnapcodeOilField.Location)
  SpanLocation = System.Span(KnapcodeOilField.Location)
  ArrayLocation = System.Array(KnapcodeOilField.Location)
  QueueLocation = System.Queue(KnapcodeOilField.Location)
end)
System.namespace("Knapcode.FactorioTools.OilField", function (namespace)
  namespace.class("Validate", function (namespace)
    local PipesAreConnected, UndergroundPipesArePipes, PipesDoNotMatch, BeaconsDoNotOverlap, NoExistingBeacons, NoOverlappingEntities, CandidateCoversMoreEntities, CountUnheatedTargets, 
    NoUnheatedBeacons, HeatPipesAreConnected, AllEntitiesHavePower
    PipesAreConnected = function (context, optimizedPipes)
      if context.Options.ValidateSolution then
        for _, terminals in System.each(context.CenterToTerminals:getValues()) do
          if #terminals ~= 1 then
            System.throw(KnapcodeFactorioTools.FactorioToolsException("A pumpjack has more than one terminal."))
          end
        end

        local goals = context:GetLocationSet2(true)
        for _, terminals in System.each(context.CenterToTerminals:getValues()) do
          for i = 0, #terminals - 1 do
            goals:Add(terminals:get(i).Terminal)
          end
        end

        local clone = KnapcodeOilField.ExistingPipeGrid(context.Grid, optimizedPipes)
        local start = KnapcodeFactorioTools.CollectionExtensions.First(goals:EnumerateItems(), KnapcodeOilField.Location)
        goals:Remove(start)
        local result = KnapcodeOilField.Dijkstras.GetShortestPaths(context, clone, start, goals, false, true)
        local reachedGoals = result.ReachedGoals
        reachedGoals:Add(start)
        local unreachedGoals = context:GetLocationSet(goals)
        unreachedGoals:ExceptWith(reachedGoals)
        if unreachedGoals:getCount() > 0 then
          -- Visualizer.Show(context.Grid, optimizedPipes.Select(p => (IPoint)new Point(p.X, p.Y)), Array.Empty<IEdge>());
          System.throw(KnapcodeFactorioTools.FactorioToolsException("The pipes are not fully connected."))
        end
      end
    end
    UndergroundPipesArePipes = function (context, pipes, locationToDirection)
      if context.Options.ValidateSolution then
        local missing = KnapcodeFactorioTools.CollectionExtensions.ToSet(locationToDirection:getKeys(), context, true)
        missing:ExceptWith(pipes)

        if missing:getCount() > 0 then
          System.throw(KnapcodeFactorioTools.FactorioToolsException("The underground pipes should be in the pipe set."))
        end
      end
    end
    PipesDoNotMatch = function (context, pipes1, pipes2)
      if context.Options.ValidateSolution then
        if pipes1:SetEquals(pipes2) then
          System.throw(KnapcodeFactorioTools.FactorioToolsException("The two pipe configurations should not match."))
        end
      end
    end
    BeaconsDoNotOverlap = function (context, solutions)
      if context.Options.ValidateSolution and not context.Options.OverlapBeacons then
        for _, solution in System.each(solutions) do
          local beaconCenterToCoveredCenters = KnapcodeOilField.Helpers.GetProviderCenterToCoveredCenters(context, context.Options.BeaconWidth, context.Options.BeaconHeight, context.Options.BeaconSupplyWidth, context.Options.BeaconSupplyHeight, solution.Beacons, true, false)

          local coveredCenterToPoleCenters = KnapcodeOilField.Helpers.GetCoveredCenterToProviderCenters(context, beaconCenterToCoveredCenters)

          for _, default in System.each(coveredCenterToPoleCenters:EnumeratePairs()) do
            local pumpjackCenter, beaconCenters = default:Deconstruct()
            if beaconCenters:getCount() > 1 then
              System.throw(KnapcodeFactorioTools.FactorioToolsException("Multiple beacons are providing an effect to a pumpjack."))
            end
          end
        end
      end
    end
    NoExistingBeacons = function (context, existingBeacons)
      if context.Options.ValidateSolution and existingBeacons:getCount() > 0 then
        System.throw(KnapcodeFactorioTools.FactorioToolsException("There should not be any existing beacons."))
      end
    end
    NoOverlappingEntities = function (context, optimizedPipes, undergroundPipes, beaconSolutions)
      if context.Options.ValidateSolution then
        if beaconSolutions == nil then
          local clone = KnapcodeOilField.PipeGrid(context.Grid)
          KnapcodeOilField.AddPipeEntities.Execute1(context, clone, optimizedPipes, undergroundPipes, false)
        else
          for _, solution in System.each(beaconSolutions) do
            local clone = KnapcodeOilField.PipeGrid(context.Grid)
            KnapcodeOilField.AddPipeEntities.Execute1(context, clone, optimizedPipes, undergroundPipes, false)
            KnapcodeOilField.Helpers.AddBeaconsToGrid(clone, context.Options, solution.Beacons)
          end
        end
      end
    end
    CandidateCoversMoreEntities = function (context, poweredEntities, coveredEntities, candidate, candidateInfo)
      if context.Options.ValidateSolution then
        local covered = candidateInfo.Covered
        local isSubsetOf = true
        do
          local i = 0
          while i < #poweredEntities and isSubsetOf do
            if covered:get(i) then
              isSubsetOf = coveredEntities:get(i)
            end
            i = i + 1
          end
        end

        if isSubsetOf then
          -- Visualizer.Show(context.Grid, new[] { candidate }.Select(p => (DelaunatorSharp.IPoint)new DelaunatorSharp.Point(p.X, p.Y)), Array.Empty<DelaunatorSharp.IEdge>());
          System.throw(KnapcodeFactorioTools.FactorioToolsException("Candidate " .. System.toString(candidate) .. " should have been eliminated."))
        end
      end
    end
    CountUnheatedTargets = function (context, unheatedPumpjacks, unheatedPipes)
      unheatedPumpjacks = 0
      unheatedPipes = 0

      if not context.Options.AddHeatPipes or context.HeatPipes == nil then
        return unheatedPumpjacks, unheatedPipes
      end

      local adjacent = SpanLocation.ctorArray(ArrayLocation(4))


      for _, location in System.each(context.Grid:getEntityLocations():EnumerateItems()) do
        local continue
        repeat
          if not System.is(context.Grid:get(location), KnapcodeOilField.Pipe) then
            continue = true
            break
          end

          context.Grid:GetAdjacent(adjacent, location)
          local heated = false
          do
            local i = 0
            while i < adjacent:getLength() and not heated do
              heated = adjacent:get(i).IsValid and System.is(context.Grid:get(adjacent:get(i)), KnapcodeOilField.HeatPipe)
              i = i + 1
            end
          end

          if not heated then
            unheatedPipes = unheatedPipes + 1
          end
          continue = true
        until 1
        if not continue then
          break
        end
      end

      for c = 0, #context.Centers - 1 do
        local center = context.Centers:get(c)
        local heated = false
        do
          local i = 0
          while i < #KnapcodeOilField.AddHeatPipes.PumpjackRingOffsets and not heated do
            local ringLocation = center:Translate1(KnapcodeOilField.AddHeatPipes.PumpjackRingOffsets:get(i))
            heated = context.Grid:IsInBounds(ringLocation) and System.is(context.Grid:get(ringLocation), KnapcodeOilField.HeatPipe)
            i = i + 1
          end
        end

        if not heated then
          unheatedPumpjacks = unheatedPumpjacks + 1
        end
      end
      return unheatedPumpjacks, unheatedPipes
    end
    NoUnheatedBeacons = function (context)
      if not context.Options.ValidateSolution or not context.Options.AddHeatPipes or not context.Options.AddBeacons or context.HeatPipes == nil then
        return
      end

      local grid = context.Grid
      local width = context.Options.BeaconWidth
      local height = context.Options.BeaconHeight

      local adjacent = SpanLocation.ctorArray(ArrayLocation(4))


      for _, location in System.each(grid:getEntityLocations():EnumerateItems()) do
        local continue
        repeat
          if not System.is(grid:get(location), KnapcodeOilField.BeaconCenter) then
            continue = true
            break
          end

          local minX = location.X - (System.div((width - 1), 2))
          local maxX = location.X + (System.div(width, 2))
          local minY = location.Y - (System.div((height - 1), 2))
          local maxY = location.Y + (System.div(height, 2))

          local heated = false
          do
            local x = minX
            while x <= maxX and not heated do
              do
                local y = minY
                while y <= maxY and not heated do
                  grid:GetAdjacent(adjacent, KnapcodeOilField.Location(x, y))
                  for i = 0, adjacent:getLength() - 1 do
                    local n = adjacent:get(i)
                    if n.IsValid and System.is(grid:get(n), KnapcodeOilField.HeatPipe) then
                      heated = true
                      break
                    end
                  end
                  y = y + 1
                end
              end
              x = x + 1
            end
          end

          if not heated then
            System.throw(KnapcodeFactorioTools.FactorioToolsException("A beacon was left without an adjacent heat pipe on Aquilo, so it would freeze."))
          end
          continue = true
        until 1
        if not continue then
          break
        end
      end
    end
    HeatPipesAreConnected = function (context)
      if context.Options.ValidateSolution and context.Options.AddHeatPipes and context.HeatPipes ~= nil and context.HeatPipes:getCount() > 0 then
        local heatPipes = context.HeatPipes
        local visited = context:GetLocationSet1()
        local queue = QueueLocation()
        local start = KnapcodeFactorioTools.CollectionExtensions.First(heatPipes:EnumerateItems(), KnapcodeOilField.Location)
        queue:Enqueue(start)
        visited:Add(start)
        local reached = 1

        local adjacent = SpanLocation.ctorArray(ArrayLocation(4))


        while #queue > 0 do
          local current = queue:Dequeue()
          context.Grid:GetAdjacent(adjacent, current)
          for i = 0, adjacent:getLength() - 1 do
            local next = adjacent:get(i)
            if next.IsValid and heatPipes:Contains(next) and visited:Add(next) then
              reached = reached + 1
              queue:Enqueue(next)
            end
          end
        end

        if reached ~= heatPipes:getCount() then
          System.throw(KnapcodeFactorioTools.FactorioToolsException("The heat pipe network is not fully connected, so heat from a single source would not reach all of it."))
        end
      end
    end
    AllEntitiesHavePower = function (context)
      if context.Options.ValidateSolution then
        local poweredEntities
        poweredEntities, _ = KnapcodeOilField.Helpers.GetPoweredEntities(context):Deconstruct()

        local electricPoleCenters = ListLocation()
        for _, location in System.each(context.Grid:getEntityLocations():EnumerateItems()) do
          local entity = context.Grid:get(location)
          if System.is(entity, KnapcodeOilField.ElectricPoleCenter) then
            electricPoleCenters:Add(location)
          end
        end

        KnapcodeOilField.Helpers.GetElectricPoleCoverage(context, poweredEntities, electricPoleCenters)
      end
    end
    return {
      PipesAreConnected = PipesAreConnected,
      UndergroundPipesArePipes = UndergroundPipesArePipes,
      PipesDoNotMatch = PipesDoNotMatch,
      BeaconsDoNotOverlap = BeaconsDoNotOverlap,
      NoExistingBeacons = NoExistingBeacons,
      NoOverlappingEntities = NoOverlappingEntities,
      CandidateCoversMoreEntities = CandidateCoversMoreEntities,
      CountUnheatedTargets = CountUnheatedTargets,
      NoUnheatedBeacons = NoUnheatedBeacons,
      HeatPipesAreConnected = HeatPipesAreConnected,
      AllEntitiesHavePower = AllEntitiesHavePower
    }
  end)
end)
