name: Continuous integration

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

permissions:
  contents: read

env:
  BUILD_PATH: "./src/vue"

jobs:
  build-vue:
    name: Build front-end
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: ${{ env.BUILD_PATH }}/package-lock.json

      - name: Restore dependencies
        run: npm install
        working-directory: ${{ env.BUILD_PATH }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.BUILD_PATH }}

      - name: Test
        run: npm run test
        working-directory: ${{ env.BUILD_PATH }}

  test-lua:
    name: Test .NET with Lua settings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Restore workloads
        run: dotnet workload restore

      - name: Restore dependencies
        run: dotnet restore

      - name: Build debug, with Lua settings
        run: dotnet build --configuration Debug /p:UseLuaSettings=true

      - name: Build release, with Lua settings
        run: dotnet build --configuration Release /p:UseLuaSettings=true

      - name: Test with Lua settings
        run: dotnet test --no-build --configuration Release --logger "console;verbosity=normal"

  test-default:
    name: Test .NET with default settings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Restore workloads
        run: dotnet workload restore

      - name: Restore dependencies
        run: dotnet restore

      - name: Build debug, no hash sets
        run: dotnet build --configuration Debug /p:UseHashSets=false

      - name: Build debug, no bit array
        run: dotnet build --configuration Debug /p:UseBitArray=false

      - name: Build debug, location as class
        run: dotnet build --configuration Debug /p:LocationAsStruct=false

      - name: Build debug, no shared instances
        run: dotnet build --configuration Debug /p:UseSharedInstances=false

      - name: Build debug, no vectors
        run: dotnet build --configuration Debug /p:UseVectors=false

      - name: Build debug, no stackalloc
        run: dotnet build --configuration Debug /p:UseStackalloc=false

      - name: Build debug, rent neighbors
        run: dotnet build --configuration Debug /p:RentNeighbors=true

      - name: Build debug, allow dynamic FLUTE degree
        run: dotnet build --configuration Debug /p:AllowDynamicFluteDegree=true

      - name: Build debug, no grid ToString
        run: dotnet build --configuration Debug /p:EnableGridToString=false

      - name: Build release with default settings
        run: dotnet build --configuration Release

      - name: Test with default settings
        run: dotnet test --no-build --configuration Release --logger "console;verbosity=normal"

      - name: Publish
        run: dotnet publish src/WebApp --configuration Release --output src/WebApp/bin/publish --runtime linux-x64 --no-self-contained /p:PublishReadyToRun=true
